#------------------------------------------------------------------#
# must check the direction of data_root and result_root before run #
#------------------------------------------------------------------#

#configure feature path
# **** please must modify the data_root before first running ****
#data_root:  /data/LI MENG RAN/HGNN-master/data
#modelnet40_ft: '/data/LI MENG RAN/HGNN-master/data/ModelNet40_mvcnn_gvcnn.mat'
#ntu2012_ft: '/data/LI MENG RAN/HGNN-master/data/NTU2012_mvcnn_gvcnn.mat'
#student_ft: '/data/LI MENG RAN/HGNN-master/data/student.txt'
#student_label_ft: '/data/LI MENG RAN/HGNN-master/data/studen_label.txt'

#Hypergraph
graph_type: &g_t hypergraph
#K_neigs: [5]
K_neigs: [2]
m_prob: 1.0
is_probH: True
#---------------------------------------
# change me
use_mvcnn_feature_for_structure: False
use_gvcnn_feature_for_structure: False
use_st_feature_for_structure: True
#---------------------------------------


#Model
#--------------------------------------------------
# select the dataset you use, ModelNet40 or NTU2012
on_dataset: &o_d ModelNet40
#on_dataset: &o_d NTU2012
#on_dataset: &o_d student
#--------------------------------------------------

#---------------------------------------
# change me
use_mvcnn_feature: False
use_gvcnn_feature: False
use_st_feature: True
#---------------------------------------


#Result
# configure result path
# **** please must modify the result_root before first running ****
#result_root: /data/LI MENG RAN/HGNN-master/result
#result_sub_folder: '/data/LI MENG RAN/HGNN-master/result/ckpt'
#ckpt_folder: '/data/LI MENG RAN/HGNN-master/result/ckpt'


#Train
max_epoch: 10000
n_hid: 128
lr: 0.001
milestones: [100]
gamma: 0.9
drop_out: 0.5
print_freq: 100
weight_decay: 0.0005
decay_step: 200
decay_rate: 0.7